- helm/charts/hpe-csi-driver/templates/hpe-csi-crd.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- helm/charts/hpe-csi-driver/values.yaml
- yaml/csi-driver/csi-hpe-v1.0.0.yaml
- yaml/csi-driver/csi-hpe-v1.1.0.yaml
- Clone from PVC require 'v1.4.0-rc1' until we have GA build available. This is due to a bug in the external-provisioner that was fixed in the RC build.
> Updated yamls to add support for pods inline volumes and Clone from Pvc workflows

- helm/charts/hpe-flexvolume-driver/questions.yml
- helm/charts/hpe-flexvolume-driver/templates/hpe-config.yaml
- helm/charts/hpe-flexvolume-driver/templates/hpe-doryd.yaml
- helm/charts/hpe-flexvolume-driver/templates/hpe-flexvolume-plugin.yaml
- Requires bugfix from @shivamerla to ensure we don't overwrite `nimble.json` during setup.
- Deploy/re-deploy driver tested
- Re-deploy of driver caused problems as the cleanup processes from previous deployment removed the `hpe.com~driver` directory where I initially put the `driver.json` file. This ended up being a stale file-handle due to the internal cleanup processes we execute on shutdown. Copying the the `driver.json` file during `postStart` from the `ConfigMap` instead seemed like a good non-intrusive middle road.
- Provision/attach/mount/umount/detach/delete passed with MariaDB from the Rancher catalog
> Support for Rancher 2.3+

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-crd.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- helm/charts/hpe-csi-driver/templates/sc.yaml
this fixes feature enablement and image tag selection when using a patch release (e.g., 1.14.7) of k8s
> use caret range comparisons for minor version checks

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
- helm/charts/hpe-csi-driver/templates/post-install.yaml
- helm/charts/hpe-csi-driver/values.yaml
This makes the container image behavior configurable by cluster operators.  Previous behavior is retained by default.
> Enhance container image definitions

- helm/charts/hpe-csi-driver/values.yaml
the value is already only set if the version is >= 1.14.  a default value should be defined so the user knows it is available to set without having to read the template.
> add missing default value for allowVolumeExpansion

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/values.yaml
* Problem:
* k8s semversion checks were using Caret range comparision, which include only major level changes.
* but the intention was to only allow patch level range checks
* Replace caret range comparition with Tilde comparision operator for matching patch ranges
* Testing: helm install
* Review: gcostea, sbyadarhalli
* Bug: https://nimblejira.nimblestorage.com/browse/NLT-
> csi-helm: fix semversion checks for patch versions

- helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
- helm/charts/hpe-flexvolume-driver/templates/hpe-doryd.yaml
- helm/charts/hpe-flexvolume-driver/templates/hpecv-cp.yaml
- yaml/csi-driver/nimble-csp.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-aws-flexvolume-driver.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-azure-flexvolume-driver.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-cp.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-flexvolume-driver.yaml
Thus during node eviction or drain, they are always guaranteed to run.
> Mark CSP/CP/Doryd pods as system-critical for guaranteed scheduling.

- helm/charts/hpe-flexvolume-driver/values.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-aws-flexvolume-driver-v3.1.0.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-azure-flexvolume-driver-v3.1.0.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-cp-v3.1.0.yaml
- yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-flexvolume-driver-v3.1.0.yaml
- yaml/flexvolume-driver/hpe-nimble-storage/hpe-flexvolume-driver-v3.1.0.yaml
Remove OCP mount directories for EKS/AKS deployments.
> Update all FlexVolume driver yaml/helm charts to point to 3.1.0 images.

- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- yaml/csi-driver/hpe-csi-k8s-1.12.yaml
- yaml/csi-driver/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/hpe-csi-k8s-1.16.yaml
* Problem:
- imagePullPolicy:Always was missing for csi node registrar image
* Testing:
* Bug: https://nimblejira.nimblestorage.com/browse/CON-
> update imagePullPolicy for csi node registrar image

- helm/charts/hpe-csi-driver/README.md
- helm/charts/hpe-csi-driver/files/config.json
- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/templates/hpe-linux-config.yaml
- helm/charts/hpe-csi-driver/values.yaml
- operators/hpe-csi-operator/README.md
- operators/hpe-csi-operator/install.sh
- yaml/csi-driver/hpe-csi-k8s-1.12.yaml
- yaml/csi-driver/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/hpe-linux-config.yaml
* Problem:
* currently our drivers are applying changes from fixed template and not user
* configurable. settings like queue_depth, max_sectors_kb should be configurable
* based on workloads.
* Added config-map called hpe-linux-config with all template settings we have
* User can edit as required and re-deploy node plugin to apply those changes
* This will be first stage of changes for csi1.0 and later can be modified to control
* 3par multipath settings etc.
* Testing: deployed using helm/yaml and verified settings are applied.
* Review: gcostea, rkumar, sbyadarahalli
* Bug: https://nimblejira.nimblestorage.com/browse/NLT-
> csi-driver: make linux iscsi/disk/multipath tuning configurable

- helm/charts/hpe-csi-driver/templates/hpe-csi-crd.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- yaml/csi-driver/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/hpe-csi-k8s-1.17.yaml
A couple of nice to have suggestions on their 1.13 driver manifest:
https://github.com/hpe-storage/co-deployments/blob/master/yaml/csi-driver/hpe-csi-k8s-1.13.yaml
1. Remove installation of csinode and csidriver alpha CRDs. Those alpha features are disabled in Anthos 1.1, so the
driver needs to (and is) functioning without those.
2. Use apps/v1 for the driver DaemonSet. This will be more future proof for when apps/v1beta2 is removed in 1.16:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
3. Remove clusterrole and binding for node-driver-registrar. Version 1.1.0 doesn't require any kubernetes rbacs.
4. It's recommended that system-critical DaemonSets include a blanket toleration so that they will never be evicted: …
> Implement suggestions by Google on HPE CSI driver.

- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
* Problem:
* Since mount/unmount are now done under /host(chroot), mounts under this needs to be
* propagated back to host
* Propagate mounts done with /host as root.
* Testing: ran integration tests on both Ubuntu 18.04 and CentOS 7.6
* Review: gcostea, rkumar, sbyadarahalli
* Bug: https://nimblejira.nimblestorage.com/browse/NLT-
> csi: propagate mounts under /host to host

- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- operators/hpe-csi-operator/deploy/rbac.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
* Bug: https://nimblejira.nimblestorage.com/browse/NLT-
> Update csi-driver cluster role to be able to delete hpenodeinfo objects

- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
* Problem:
Hitting the following issues
https://github.com/kubernetes/kubernetes/issues/84169
https://github.com/kubernetes/kubernetes/issues/86281
The problem is described in the comment below
https://github.com/kubernetes/kubernetes/issues/84169#issuecomment-545692734
```
* Kubernetes volume layer has code to periodically verify that volumes are attached.
It triggers every minute by default.
* For CSI, the Kubernetes volume code has NOT implemented "bulk verify volume attach", so kubernetes falls back to calling verify volumes attached PER NODE.
* The Kubernetes CSI code fetches a VolumeAttachment FOR EVERY ATTACHED VOLUME on the specified node as part of VolumesAreAttached(...) to check that it is verified.
kubernetes/pkg/volume/csi/csi_attacher.go
* Line 199 in 037751e
attach, err := …
```
> update csi attacher

- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
* Problem:
- there seems to still issues with drain when with
reconcile sync fix https://github.com/kubernetes/kubernetes/issues/86281#issuecomment-589780854
setting disable-attach-detach-reconcile-sync to true in controller-manager as a work around fix 
* Testing:
- create,delete and drain tests
> revert reconcile-sync fix

- build_tools/artifactory_search.json
* Problem:
currently it looks for latest builds
search for v1.1.0 as well as edge
* Testing:
"path": "dcs-docker-local/hpestorage/nimble-csp/v1.1.0-2"
"path": "dcs-docker-local/hpestorage/nimble-csp/edge-315"
> update csp artifactory search

- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
* Problem:
* controller/node driver need rbac to get/list/update pv's with label for nfs
* node driver needs NODE_NAME env to use for hpenodeinfos.
* Added required RBAC for get/list/update of PVs
* Pass NODE_NAME env from pod spec.
* Testing: deployed on 1.17
* Review: gcostea, rkumar
> co-deployments: update rbac for nfs and add node_name env

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
* Problem:
* Pod monitor requires RBAC to check pods on dead nodes and delete them.
* Pod monitor requires RBAC to check and delete volumeattachments from dead nodes.
* CSI controller plugin needs to invoke host utilities(dnsdomainname), using chroot.
* Add required RBAC to csi-provisioner-role and mount root fs as /host with controller plugin.
* Testing: deployment on 1.17 and 1.18
* Review: gcostea, rkumar
> co-deployments: add rbac required for pod monitor

- build_tools/artifactory_search.json
- the image search should follow up with a build number to not confuse with private builds
> update artifactory search for edge images for automation

- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
Hi Shiva,
Added rbac for pvc,namespaces,secrets, storageclass to support virtualCopyOf,cloneOf and replication  features for 3PAR CSP.
Please review
Regards
Bhagyashree Sarawate
> Aded rbac for 3par to support virtualcopyof,cloneof and replication

- helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
- helm lint didn't catch the error
- error was thrown as part of helm install --dry-run
install.go:180: [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: YAML parse error on hpe-csi-driver/templates/nimble-csp.yaml: error converting YAML to JSON: yaml: line 20: did not find expected '-' indicator
helm.go:75: [debug] error converting YAML to JSON: yaml: line 20: did not find expected '-' indicator
YAML parse error on hpe-csi-driver/templates/nimble-csp.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
> helm: lint fix

- crd/snapshotgroup/storage.hpe.com_snapshotgroupclasses.yaml
- crd/snapshotgroup/storage.hpe.com_snapshotgroupcontents.yaml
- crd/snapshotgroup/storage.hpe.com_snapshotgroups.yaml
- crd/volumegroup/storage.hpe.com_volumegroupclasses.yaml
- crd/volumegroup/storage.hpe.com_volumegroupcontents.yaml
- crd/volumegroup/storage.hpe.com_volumegroups.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
- yaml/csi-driver/edge/nimble-csp.yaml
- instead of automatically installing the crds, give the option to instal the crd
via yaml file to be deployed by the user
- push 1.4.0-beta images for yaml files
> crd: add new snapshotgroup/volumegroup crds to be deployed

- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
The csi-node-driver-registrar container in the hpe-csi-node daemonset defines
a pre-stop hook that runs a command in the container.  However, the container
does not include a shell command, so the hook execution fails with this error:
"exec: \"/bin/sh\": stat /bin/sh: no such file or directory".  Avoid the error
by removing the hook.
> CON-1395: Avoid FailedPreStopHook warning on hpe-csi-node termination

- helm/charts/hpe-csi-driver/README.md
- helm/charts/hpe-csi-driver/templates/cv-csp.yaml
- helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
- helm/charts/hpe-csi-driver/templates/primera-3par-csp.yaml
- helm/charts/hpe-csi-driver/values.yaml
Thank you community users @papanito and @Baykonur for this suggestion. This PR supersede PRs #225 and #218 in addition to:
- Cleaning up the default values file and table by organizing variables alphabetically.
- This change does not alter the current behavior of the chart and users need to selectively disable the unwanted CSPs.
- The `flavor` variable was not used anywhere in the chart. Removed.
> CSP selector and values.yaml cleanup

- yaml/csi-driver/edge/3par-primera-csp.yaml
- yaml/csi-driver/edge/cv-csp.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.20.yaml
- yaml/csi-driver/edge/nimble-csp.yaml
- yaml/csi-driver/v1.4.0/3par-primera-csp.yaml
- yaml/csi-driver/v1.4.0/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/v1.4.0/hpe-csi-k8s-1.18.yaml
- yaml/csi-driver/v1.4.0/hpe-csi-k8s-1.19.yaml
- yaml/csi-driver/v1.4.0/hpe-csi-k8s-1.20.yaml
- yaml/csi-driver/v1.4.0/nimble-csp.yaml
Accidentally nuked my previous branch.
This PR brings the tolerations we've set in the Helm chart to the raw YAML files.
> Consistent tolerations between Helm/Operator and Advanced Install

- helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.20.yaml
Reverting [PR#238](https://github.com/hpe-storage/co-deployments/pull/238) to read the secrets from all namespaces as per the discussion .
@sneharai4 @raunakkumar please review
> Reverting changes to read secrets from all namespaces

- operators/hpe-csi-operator/deploy/crds/storage.hpe.com_hpecsidrivers_crd.yaml
- operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
- operators/hpe-csi-operator/deploy/generated/api/v1/hpecsidriver_types.go
Problem:
- with the introductions of helm schema checks, operator installations fail because of invalid
params
> remove flavor from hpe csi driver operator CR definition

- operators/hpe-csi-operator/Dockerfile
Problem: redhat cert suite found critical_vulnerabilities with 1.3 version,
after updating it to 1.8, the cert security suite passed
https://quay.io/repository/operator-framework/helm-operator?tab=tags 1.8 is the minimum version with no vulnerabilities
> update helm-operator image

- helm/charts/hpe-array-exporter/Chart.yaml
- helm/charts/hpe-array-exporter/README.md
- helm/charts/hpe-array-exporter/templates/hpe-array-exporter.yaml
- helm/charts/hpe-array-exporter/templates/tests/test-hpe-array-exporter.yaml
- helm/charts/hpe-array-exporter/values.yaml
- helm/charts/hpe-csi-info-metrics/Chart.yaml
- helm/charts/hpe-csi-info-metrics/README.md
- helm/charts/hpe-csi-info-metrics/templates/hpe-csi-info-metrics.yaml
- helm/charts/hpe-csi-info-metrics/templates/tests/test-hpe-csi-info-metrics.yaml
- helm/charts/hpe-csi-info-metrics/values.yaml
- helm/values/array-exporter/v1.0.0/values.yaml
- helm/values/csi-info-metrics/v1.0.0/values.yaml
- yaml/array-exporter/edge/hpe-array-exporter.yaml
- yaml/array-exporter/v1.0.0/hpe-array-exporter.yaml
- yaml/csi-info-metrics/edge/hpe-csi-info-metrics.yaml
* In the hpe-array-exporter and hpe-csi-info-metrics Helm charts, add a test
case to validate the basic function of a release (installed chart).
* Update to Helm API version 2.
* Add a Kubernetes version constraint of 1.18+.
> Add a smoke test for each of the metrics Helm charts

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
When using a private registry, `csi-snapshotter` points to a wrong namespace.
Since the CSI driver 2.0, the new `csi-snapshotter` is at `sig-storage` and not `k8scsi` used in former versions
> [csi-snapshotter][4.0.0] fix private registry namespace

- yaml/csi-driver/edge/hpe-csi-k8s-1.22.yaml
The attacher needed an update. Lightweight testing only.
This is the diff against 1.21:
```
137c137
<           image: k8s.gcr.io/sig-storage/csi-attacher:v2.2.0
---
>           image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
368c368
<     verbs: ["get", "list", "watch", "update", "create", "delete"]
---
>     verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
```
Signed-off-by: Michael Mattsson <michael.mattsson@gmail.com>
> Initial K8s 1.22 tire kicking

- helm/charts/hpe-csi-driver/values.schema.json
When charts are linted at a macro level, such as the Rancher partner repo or a chart is a sub chart being dependent on elsewhere, the global attribute needs to be defined as empty in the schema. We do not have to push a new chart at this time as the diff is managed separately with Rancher but it's an extra step to keep track of.
```
~/code/co-deployments/helm/charts/hpe-csi-driver$ helm lint
==> Linting .
1 chart(s) linted, 0 chart(s) failed
~/code/co-deployments/helm/charts/hpe-csi-driver$ git diff HEAD~1
diff --git a/helm/charts/hpe-csi-driver/values.schema.json b/helm/charts/hpe-csi-driver/values.schema.json
index 99c21a8..e8085b0 100644
--- a/helm/charts/hpe-csi-driver/values.schema.json
+++ b/helm/charts/hpe-csi-driver/values.schema.json
@@ -163,7 +163,8 @@
"default": 60,
"minimum": …
```
> Global attribute

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.22.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.23.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.24.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.25.yaml
SIG storage is transitioning the registry DNS name to registry.k8s.io.
Signed-off-by: Michael Mattsson <michael.mattsson@gmail.com>
> Update canonical name for SIG storage images

- helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.24.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.25.yaml
- yaml/csi-driver/edge/hpe-csi-k8s-1.27.yaml
Passes CSI e2e on Kubernetes 1.27. Does not include HPE CSI/CSP specific tests. Requires full QA validation and sign offs.
```
[ReportAfterSuite] Kubernetes e2e JUnit report
test/e2e/framework/test_context.go:593
[ReportAfterSuite] PASSED [0.113 seconds]
------------------------------
Ran 91 of 7486 Specs in 4797.250 seconds
SUCCESS! -- 91 Passed | 0 Failed | 0 Pending | 7395 Skipped
PASS
```
> Update SIG Storage images

- operators/hpe-csi-operator/.gitignore
- operators/hpe-csi-operator/Makefile
- operators/hpe-csi-operator/README.md
The next build will separate the bundle between community and certified. The certified will use the kube rbac proxy advised by Red Hat.
- https://redhat-connect.gitbook.io/certified-operator-guide/helm-operators/building-a-helm-operator/update-the-controller-manager
The increase in memory for the controller manager (L55) stems from an issue a customer is suffering from.
> Separate community/certified bundles

- helm/charts/hpe-csi-driver/README.md
- helm/charts/hpe-csi-driver/templates/pre-install-hook.yaml
- helm/charts/hpe-csi-driver/values.schema.json
- helm/charts/hpe-csi-driver/values.yaml
When using Argo CD the pre-install hook will cause a deadlock as Argo CD cannot use the `lookup` function from Helm (See https://github.com/argoproj/argo-cd/issues/4331).
This PR introduces a switch to disable the pre-install hook.
> Add option to disable pre-install hook

- helm/charts/hpe-csi-driver/README.md
- helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
- helm/charts/hpe-csi-driver/values.schema.json
- helm/charts/hpe-csi-driver/values.yaml
- operators/hpe-csi-operator/Makefile
- operators/hpe-csi-operator/sources/hpe-csi-operator.csv.yaml
- operators/hpe-csi-operator/sources/hpecsidrivers.storage.hpe.com.crd.yaml
- Fix to allow testing of CON-3023/IDEA-542
- Added disablePreInstallHooks to Operator
- Changed operator build to use a local chart as source instead of being hardcoded to co-deployments. This allows testing of features simultaneously of the Helm chart and Operator build and submit a single PR.
> Max volumes per node and operator build fixes

- operators/hpe-csi-operator/.gitignore
- operators/hpe-csi-operator/Makefile
- Builds helm-operator in `$(REPO_NAME)` (quay.io/yourreponame)
- Substitutes FROM with tag from previous step for final csi-driver-operator* images
- Operator SDK updated to latest
> Build helm-operator from latest operator-sdk with latest UBI9

- helm/charts/hpe-cosi-driver/Chart.yaml
- helm/charts/hpe-cosi-driver/templates/tests/test-hpe-cosi-driver.yaml
Verified COSI helm charts through chart-verifier tool (https://github.com/redhat-certification/chart-verifier) as a pre-requisite for Red Hat(OpenShift) certification.
1. Add a NOTES.txt for COSI chart (Non-Mandatory check)
2. Added a test file for COSI helm chart.
3. Added Openshift annotations & kube version under Chart.yaml
[chart-verifier-tool-results.txt](https://github.com/user-attachments/files/20010296/chart-verifier-tool-results.txt)
Continuing discussions from
https://github.com/hpe-storage/co-deployments/pull/418
> AS-202640: Updating charts based on checks in chart-verifier tool

- helm/charts/hpe-cosi-driver/templates/deployment.yaml
Updating the Helm chart to support Kubernetes 1.24+ and the latest sidecar image. It adds explicit securityContext settings to run containers as non-root, and includes projected service account token handling to ensure proper API authentication, addressing changes in Kubernetes service account token management.
Reason for change : New Sidecar image fails with the current helm chart.
> Adding explicit securityContext settings to Helm Chart to support latest sidecar image

- helm/charts/hpe-array-exporter/README.md
- helm/charts/hpe-array-exporter/templates/hpe-array-exporter.yaml
- helm/charts/hpe-array-exporter/values.schema.json
- helm/charts/hpe-array-exporter/values.yaml
- helm/charts/hpe-csi-info-metrics/README.md
- helm/charts/hpe-csi-info-metrics/templates/hpe-csi-info-metrics.yaml
- helm/charts/hpe-csi-info-metrics/values.schema.json
- helm/charts/hpe-csi-info-metrics/values.yaml
This PR allows setting `relabelings` and `metricRelabelings` on the `serviceMonitor` of the `hpe-array-exporter` and `hpe-csi-info-metrics` charts.
Here is an example usage, which makes the metric names consistent across all array types:
```yaml
serviceMonitor:
metricRelabelings:
- sourceLabels: [__name__]
action: labelmap
regex: "cpg|pool"
replacement: "storagepool"
- sourceLabels: [__name__]
regex: "^hpe(primera|nimble|3par|alletra6000|alletra9000)_(.*)"
targetLabel: "__name__"
replacement: "hpe_$2"
- sourceLabels: [__name__]
regex: "^hpe_(pool|cpg)_(.*)"
targetLabel: "__name__"
replacement: "hpe_storagepool_$2"
```
> Allow setting relabelings and metricRelabelings for hpe-array-exporter & hpe-csi-info-metrics
