README.md
helm/charts/hpe-csi-driver/README.md
helm/charts/hpe-flexvolume-driver/README.md

First pass on docs

---

helm/charts/hpe-csi-driver/templates/hpe-csi-crd.yaml
helm/charts/hpe-csi-driver/templates/sc.yaml
yaml/csi-driver/hpe-csi-k8s-1.13.yaml

Fixed the k8s-1.13 deployment yaml to create correct CSIDriver object

Updated with CSIDriver CRD for k8s-1.13

---

helm/charts/hpe-flexvolume-driver/templates/hpe-flexvolume-plugin.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-secret.yaml
helm/charts/hpe-flexvolume-driver/templates/hpecv-cp.yaml
helm/charts/hpe-flexvolume-driver/values.yaml
yaml/flexvolume-driver/hpecv-cp.yaml
yaml/flexvolume-driver/hpecv-flexvolume-driver.yaml

Add YAML files to deploy container-provider for cloud volumes

---

yaml/flexvolume-driver/hpecv-cp.yaml

remove args to cp service

---

yaml/flexvolume-driver/hpecv-cp.yaml

Update hpecv-cp.yaml to consider backend from secret

---

helm/charts/hpe-flexvolume-driver/README.md
helm/charts/hpe-flexvolume-driver/templates/hpe-config.yaml
helm/charts/hpe-flexvolume-driver/templates/hpecv-cp.yaml
helm/charts/hpe-flexvolume-driver/values.yaml
yaml/flexvolume-driver/hpecv-flexvolume-driver.yaml

Add volume-driver config param for CV helm charts

---

helm/charts/hpe-flexvolume-driver/README.md

Signed-off-by: Michael Mattsson <michael.mattsson@nimblestorage.com>

Make docs consistent with helm.sh

---

yaml/flexvolume-driver/hpe-flexvolume-driver.yaml

Protocol got hard coded to iscsi in 3.1 flexvolume yaml, fetch this from secret.

---

helm/charts/hpe-flexvolume-driver/Chart.yaml
helm/charts/hpe-flexvolume-driver/README.md
helm/charts/hpe-flexvolume-driver/questions.yml
helm/charts/hpe-flexvolume-driver/templates/hpe-config.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-doryd.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-flexvolume-plugin.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-secret.yaml
helm/charts/hpe-flexvolume-driver/templates/hpecv-cp.yaml
helm/charts/hpe-flexvolume-driver/templates/sc.yaml
helm/charts/hpe-flexvolume-driver/values.yaml

Update flexvolume-chart for CV deployment

---

helm/charts/hpe-flexvolume-driver/questions.yml
helm/charts/hpe-flexvolume-driver/templates/hpe-config.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-doryd.yaml
helm/charts/hpe-flexvolume-driver/templates/hpe-flexvolume-plugin.yaml
helm/charts/hpe-flexvolume-driver/values.yaml

control logLevel variable with helm and pass FLAVOR env to flexvolume

---

yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-aws-flexvolume-driver-v3.1.0.yaml
yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-azure-flexvolume-driver-v3.1.0.yaml
yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-cp-v3.1.0.yaml
yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-flexvolume-driver-v3.1.0.yaml
yaml/flexvolume-driver/hpe-cloud-volumes/hpecv-flexvolume-driver.yaml
yaml/flexvolume-driver/hpe-nimble-storage/hpe-flexvolume-driver-v3.1.0.yaml

Update YAML files with store images

---

helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-crd.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
operators/hpe-csi-operator/deploy/rbac.yaml
yaml/csi-driver/hpe-csi-k8s-1.12.yaml
yaml/csi-driver/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/hpe-csi-k8s-1.17.yaml

- deprecate volume snapshot alpha 
- add k8s 1.17 yaml for snapshot beta
* Bug: https://nimblejira.nimblestorage.com/browse/CON-619

snapshot beta changes

---

yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.17.yaml

* add linux-config map to 1.17 yamls

---

yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/v1.0.0/hpe-csi-k8s-1.17.yaml

Update images tags to 1.0.1 with nodeinfo fixes

---

helm/charts/hpe-csi-driver/README.md
helm/charts/hpe-flexvolume-driver/README.md
helm/values/csi-driver/v1.0.0/values.yaml
helm/values/csi-driver/v1.0.1/values.yaml
helm/values/csi-driver/v1.1.0-beta/values.yaml
helm/values/flexvolume-driver/v3.0.0/values.yaml
helm/values/flexvolume-driver/v3.1.0/values.yaml

Version values.yaml files for each release, as latest values might not work with old releases if used incorrectly.

---

helm/charts/package.sh

Add script to package helm charts based on chart name

---

build_tools/artifactory_search.json
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/v1.1.0/hpe-linux-config.yaml
yaml/csi-driver/v1.1.0/nimble-csp.yaml

add v1.1.0 yamls

---

yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/nimble-csp.yaml

Update edge yaml files in master with latest images

---

yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.16.yaml

Update RBAC for attacher v2.1.1 to patch persistent volumes to add finalizer.

---

operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
yaml/csi-driver/v1.1.0/3par-primera-csp.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/v1.1.0/hpe-csi-k8s-1.17.yaml

Update yaml files for 1.1.1 csi driver and add 3par csp

---

helm/charts/hpe-csi-driver/README.md
helm/charts/hpe-csi-driver/values.yaml
operators/hpe-csi-operator/deploy/crds/storage.hpe.com_hpecsidrivers_crd.yaml
operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
operators/hpe-csi-operator/deploy/generated/api/v1/hpecsidriver_types.go
operators/hpe-csi-operator/deploy/olm-catalog/hpe-csi-driver-operator/2.0.0/hpe-csi-driver-operator.v2.0.0.clusterserviceversion.yaml
operators/hpe-csi-operator/deploy/olm-catalog/hpe-csi-driver-operator/2.0.0/storage.hpe.com_hpecsidrivers_crd.yaml

Update charts and operator files for 3par after tests

---

operators/hpe-csi-operator/README.md
operators/hpe-csi-operator/deploy/scc.yaml

Update steps to deploy SCC for HPE CSI Operator

---

helm/charts/hpe-csi-driver/README.md

Signed-off-by: Sneha Rai <sneha_srai@yahoo.co.in>

Added note for SC creation for primera3par backend

---

helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
operators/hpe-csi-operator/deploy/role.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.13.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml

Enable pod monitor by default with controller plugin

---

yaml/csi-driver/v1.1.0/3par-primera-csp.yaml

HPEVolumeInfos CRD is pre-requisite for 3par/primera CSP

---

helm/charts/hpe-csi-driver/Chart.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml

Add mutator and csi-extentions-driver sidecar containers to csi controller deployment

---

build_tools/artifactory_search.json

Update search patterns to find latest mutator/extensions drivers

---

helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
helm/charts/hpe-csi-driver/templates/hpe-linux-config.yaml
helm/charts/hpe-csi-driver/values.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.14.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
yaml/csi-driver/edge/hpe-linux-config.yaml

add chap configMap yaml files

---

operators/hpe-csi-operator/deploy/crds/storage.hpe.com_hpecsidrivers_crd.yaml
operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
operators/hpe-csi-operator/deploy/generated/api/v1/hpecsidriver_types.go

operator : add iscsi info to hpe csi operator crd

---

helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.15.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.16.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
yaml/csi-driver/edge/hpe-linux-config.yaml

- configMap updates are not honored.

deprecate configMap in favor of env vars for CHAP

---

build_tools/artifactory_search.json

add search for volume-group/snapshot-group

---

helm/charts/hpe-csi-driver/README.md

Signed-off-by: Michael Mattsson <michael.mattsson@nimblestorage.com>

A few issues, QA got back with K8s >= 1.14 only for CSI 1.3.0

---

build_tools/artifactory_search.json

Update artifactory search pattern to pull v1.3.0 images

---

operators/hpe-csi-operator/Dockerfile
operators/hpe-csi-operator/deploy/olm-catalog/hpe-csi-driver-operator/1.3.0/hpe-csi-operator.v1.3.0.clusterserviceversion.yaml
operators/hpe-csi-operator/deploy/operator.yaml

Update operator bundle to use v1.3.0 GA image

---

helm/charts/hpe-csi-driver/questions.yml

Signed-off-by: Michael Mattsson <michael.mattsson@nimblestorage.com>

Typo that prevents Rancher catalog integration.

---

helm/charts/hpe-csi-driver/questions.yml

- Adds partner status to Rancher Catalog
Signed-off-by: Michael Mattsson <michael.mattsson@nimblestorage.com>

Rancher 2.4 partner label

---

helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
helm/charts/hpe-csi-driver/values.yaml
operators/hpe-csi-operator/.gitignore
operators/hpe-csi-operator/deploy/crds/storage.hpe.com_hpecsidrivers_crd.yaml
operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
yaml/csi-driver/edge/nimble-csp.yaml

add registryPrefix to be configurable 
add 1.19 yaml files with updated side car images

update to add registryPrefix and include 1.19 yaml

---

helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml

- update the csi-snapshotter reference to get fixes from csi-snapshotter for pre-provisioned
snapshots
- address secretKey for Listsnapshots in snapshotClass

updat csisnapshotter image

---

build_tools/artifactory_search.json
helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-rbac.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.18.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.19.yaml
yaml/csi-driver/edge/nimble-csp.yaml

- add group provisioner as side cars to csi controller
- push images to quay.io

update group provisioner images

---

docs/artifacthub-repo.yml

Add verified publisher to Artifact Hub, part I

---

docs/artifacthub-repo.yml
docs/index.yaml

ArtifactHub, part II

---

yaml/csi-driver/edge/hpe-csi-k8s-1.17.yaml

Kind CSIDriver is v1beta1 in 1.17

---

helm/charts/hpe-csi-driver/templates/cv-csp.yaml
yaml/csi-driver/edge/cv-csp.yaml

Signed-off-by: chaitra <chaitra.kallianpur@hpe.com>

CON-1668 : Add support to deploy cv-csp using helm and operator

---

helm/charts/hpe-csi-driver/questions.yml

Rancher fixes

---

README.md
helm/charts/hpe-csi-driver/README.md

README updates

---

helm/charts/hpe-csi-driver/README.md

A few clarifications

---

yaml/csi-driver/edge/3par-primera-csp.yaml
yaml/csi-driver/v2.0.0/3par-primera-csp.yaml

fix primera csp yaml file typo

---

operators/hpe-csi-operator/deploy/operator.yaml

operator update image to 2.0.0

---

helm/charts/hpe-csi-driver/README.md
helm/charts/hpe-csi-info-metrics/Chart.yaml
helm/charts/hpe-csi-info-metrics/README.md
helm/charts/hpe-csi-info-metrics/templates/NOTES.txt
helm/charts/hpe-csi-info-metrics/templates/hpe-csi-info-metrics.yaml
helm/charts/hpe-csi-info-metrics/values.schema.json
helm/charts/hpe-csi-info-metrics/values.yaml
helm/values/csi-info-metrics/v1.0.0/values.yaml
yaml/csi-info-metrics/edge/hpe-csi-info-metrics-service-monitor.yaml
yaml/csi-info-metrics/edge/hpe-csi-info-metrics.yaml
yaml/csi-info-metrics/v1.0.0/hpe-csi-info-metrics-service-monitor.yaml
yaml/csi-info-metrics/v1.0.0/hpe-csi-info-metrics.yaml

Signed-off-by: Roger Kumpf <roger.kumpf@hpe.com>

Add preliminary Helm chart and YAML files for CSI info metrics

---

README.md
helm/charts/hpe-array-exporter/Chart.yaml
helm/charts/hpe-array-exporter/README.md
helm/charts/hpe-array-exporter/templates/NOTES.txt
helm/charts/hpe-array-exporter/templates/_helpers.tpl
helm/charts/hpe-array-exporter/templates/hpe-array-exporter.yaml
helm/charts/hpe-array-exporter/values.schema.json
helm/charts/hpe-array-exporter/values.yaml
helm/values/array-exporter/v1.0.0/values.yaml
yaml/array-exporter/edge/hpe-array-exporter-secret.yaml
yaml/array-exporter/edge/hpe-array-exporter-service-monitor.yaml
yaml/array-exporter/edge/hpe-array-exporter.yaml
yaml/array-exporter/v1.0.0/hpe-array-exporter-secret.yaml
yaml/array-exporter/v1.0.0/hpe-array-exporter-service-monitor.yaml
yaml/array-exporter/v1.0.0/hpe-array-exporter.yaml

Signed-off-by: Roger Kumpf <roger.kumpf@hpe.com>

Add preliminary Helm chart and YAML files for Array Exporter

---

build_tools/artifactory_search.json
build_tools/artifactory_upload.json

Signed-off-by: Roger Kumpf <roger.kumpf@hpe.com>

Add build support for the Array Exporter and CSI Info Metrics

---

yaml/csi-info-metrics/edge/hpe-csi-info-metrics-service-monitor.yaml
yaml/csi-info-metrics/v1.0.0/hpe-csi-info-metrics-service-monitor.yaml
yaml/csi-info-metrics/v1.0.0/hpe-csi-info-metrics.yaml

Signed-off-by: Roger Kumpf <roger.kumpf@hpe.com>

Use a consistent app label for the csi-info-metrics service

---

operators/hpe-csi-operator/deploy/role.yaml

csi: fix rbac for operator to match helm

---

helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
yaml/csi-driver/edge/nimble-csp.yaml

update alletra-6000-and-nimble-csp tag for 2.1.0-beta

---

build_tools/artifactory_search.json

ability to fetch alletra 9000 csp from artifactory

---

yaml/csi-driver/edge/hpe-csi-k8s-1.20.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.21.yaml
yaml/csi-driver/v2.1.0/hpe-csi-k8s-1.20.yaml
yaml/csi-driver/v2.1.0/hpe-csi-k8s-1.21.yaml

fix csi-attacher versioning to match helm

---

helm/charts/hpe-csi-driver/files/config.json
yaml/csi-driver/edge/hpe-linux-config.yaml

Updated config.json with the new format
Signed-off-by: Adarsh Pratik <adarsh.pratik@hpe.com>

CON-2295: Merge of multipath.conf is not comprehensive

---

operators/hpe-csi-operator/deploy/crds/storage.hpe.com_hpecsidrivers_crd.yaml

Added fix for 
https://nimblejira.nimblestorage.com/browse/CON-2737
Issue in taints and tolerations on operator Deployment

Adding detailed schema for affinity/nodeAffinity

---

yaml/csi-driver/edge/hpe-csi-k8s-1.24.yaml

- Added hpe-csi-k8s-1.24.yaml file
Signed-off-by: Adarsh Pratik <adarsh.pratik@hpe.com>

CON-2756: yaml deployment support for k8s v1.24

---

yaml/csi-driver/edge/3par-primera-crd.yaml
yaml/csi-driver/v2.1.0/3par-primera-crd.yaml
yaml/csi-driver/v2.1.1/3par-primera-crd.yaml

Signed-off-by: Madhavendra Goswami <madhavendra.goswami@hpe.com>

con-2731 single crd file

---

helm/charts/hpe-array-exporter/Chart.yaml
helm/charts/hpe-csi-driver/Chart.yaml
helm/charts/hpe-csi-info-metrics/Chart.yaml

Signed-off-by: Michael Mattsson <michael.mattsson@gmail.com>

References and security tag for future updates

---

helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.22.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.23.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.24.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.25.yaml

Signed-off-by: Michael Mattsson <michael.mattsson@gmail.com>

CVE fixed attacher

---

operators/hpe-csi-operator/deploy/role_binding.yaml

Updated rbac API version in role_binding.yaml.

Updated rbac API version

---

helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.24.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.25.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.27.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.28.yaml

NFS tolerations

---

operators/hpe-csi-operator/build.sh

v2.4.0 operator build

---

yaml/csi-driver/edge/hpe-csi-k8s-1.26.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.27.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.28.yaml
yaml/csi-driver/edge/hpe-csi-k8s-1.29.yaml

Adds an initContainer to conform the node prior to starting the driver and registrar

Added init container to edge

---

operators/hpe-csi-operator/README.md

- Fixed flowchart and spelling mistakes etc.

Updated docs

---

operators/hpe-csi-operator/Makefile
operators/hpe-csi-operator/README.md
operators/hpe-csi-operator/destinations/certified-operators/current-version/manifests/hpe-csi-operator.clusterserviceversion.yaml
operators/hpe-csi-operator/destinations/community-operators/current-version/manifests/hpe-csi-operator.v0.0.0.clusterserviceversion.yaml
operators/hpe-csi-operator/destinations/hpecsidriver-latest-sample.yaml
operators/hpe-csi-operator/destinations/hpecsidriver-v0.0.0-sample.yaml
operators/hpe-csi-operator/sources/hpe-csi-operator.csv.yaml

- Added documentation and functionality to allow easier external testing without building the artifacts.

Further refinements

---

operators/hpe-csi-operator/.gitignore
operators/hpe-csi-operator/Makefile
operators/hpe-csi-operator/README.md
operators/hpe-csi-operator/destinations/certified-operators/current-version/manifests/hpe-csi-operator.clusterserviceversion.yaml
operators/hpe-csi-operator/destinations/community-operators/current-version/manifests/hpe-csi-operator.v2.4.1.clusterserviceversion.yaml
operators/hpe-csi-operator/destinations/hpecsidriver-v2.4.1-sample.yaml

- Refined docs
- Refined build
- v2.4.1 outputs

v2.4.1 operators

---

operators/hpe-csi-operator/destinations/certified-operators/current-version/manifests/hpe-csi-operator.clusterserviceversion.yaml

Updated the SHA digest of the csi-driver-operator image as per redhat registry

v2.4.1: Update SHA digest of the csi-driver-operator image

---

operators/hpe-csi-operator/Makefile
operators/hpe-csi-operator/sources/hpe-csi-operator.csv.yaml

+ improved structure for future updates.

Add replaces field and remove redundant fields 

---

operators/hpe-csi-operator/destinations/certified-operators/current-version/manifests/hpe-csi-operator.clusterserviceversion.yaml

Updated the SHA digest of the csi-driver-operator image as per redhat registry

v2.4.2: Update SHA digest of the csi-driver-operator image

---

helm/charts/hpe-csi-driver/Chart.yaml
helm/charts/hpe-csi-driver/README.md
helm/charts/hpe-csi-driver/templates/hpe-csi-controller.yaml
helm/charts/hpe-csi-driver/templates/hpe-csi-node.yaml
helm/charts/hpe-csi-driver/templates/nimble-csp.yaml
helm/charts/hpe-csi-driver/templates/primera-3par-csp.yaml
helm/charts/hpe-csi-driver/values.schema.json
helm/charts/hpe-csi-driver/values.yaml

Image and registry reference cleanup

---

operators/hpe-csi-operator/Makefile
operators/hpe-csi-operator/README.md
operators/hpe-csi-operator/sources/annotations.certified.yaml
operators/hpe-csi-operator/sources/bundle.Dockerfile

- Complete sources to build v2.5.0 once the GA Helm chart is pushed.

v2.5.0 prep

---

operators/hpe-csi-operator/Makefile
operators/hpe-csi-operator/sources/annotations.certified.yaml
operators/hpe-csi-operator/sources/bundle.Dockerfile
operators/hpe-csi-operator/sources/operator.Dockerfile

- Passes e2e tests for RWO/RWX on OpenShift 4.18-rc6

OpenShift changes
